-- Create hr_manual_deductions table
CREATE TABLE IF NOT EXISTS `hr_manual_deductions` (
  `id` VARCHAR(191) NOT NULL,
  `companyId` VARCHAR(191) NOT NULL,
  `employeeId` VARCHAR(191) NOT NULL,
  `type` ENUM('LATE', 'ABSENCE', 'EARLY_LEAVE', 'VIOLATION', 'DAMAGE', 'OTHER') NOT NULL DEFAULT 'OTHER',
  `category` VARCHAR(191) NULL,
  `amount` DECIMAL(10, 2) NOT NULL,
  `reason` TEXT NOT NULL,
  `description` TEXT NULL,
  `date` DATE NOT NULL,
  `effectiveMonth` INT NOT NULL,
  `effectiveYear` INT NOT NULL,
  `status` ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
  `approvedBy` VARCHAR(191) NULL,
  `approvedAt` DATETIME(3) NULL,
  `rejectedBy` VARCHAR(191) NULL,
  `rejectedAt` DATETIME(3) NULL,
  `rejectionReason` TEXT NULL,
  `appliedToPayroll` BOOLEAN NOT NULL DEFAULT false,
  `payrollId` VARCHAR(191) NULL,
  `attachments` TEXT NULL,
  `notes` TEXT NULL,
  `createdBy` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `hr_manual_deductions_companyId_idx` (`companyId`),
  INDEX `hr_manual_deductions_employeeId_idx` (`employeeId`),
  INDEX `hr_manual_deductions_status_idx` (`status`),
  INDEX `hr_manual_deductions_effectiveMonth_effectiveYear_idx` (`effectiveMonth`, `effectiveYear`),
  INDEX `hr_manual_deductions_createdBy_idx` (`createdBy`),
  CONSTRAINT `hr_manual_deductions_companyId_fkey` FOREIGN KEY (`companyId`) REFERENCES `companies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
