-- Add Product Page Layout Order Settings
ALTER TABLE `storefront_settings`
ADD COLUMN `productPageLayoutEnabled` BOOLEAN NOT NULL DEFAULT false COMMENT 'تفعيل التحكم في ترتيب صفحة المنتج',
ADD COLUMN `productPageOrder` TEXT NULL COMMENT 'ترتيب العناصر (JSON array)',
ADD COLUMN `productPageShowTitle` BOOLEAN NOT NULL DEFAULT true COMMENT 'عرض العنوان',
ADD COLUMN `productPageShowCategory` BOOLEAN NOT NULL DEFAULT true COMMENT 'عرض الفئة',
ADD COLUMN `productPageShowSocialSharing` BOOLEAN NOT NULL DEFAULT true COMMENT 'عرض المشاركة الاجتماعية',
ADD COLUMN `productPageShowBadges` BOOLEAN NOT NULL DEFAULT true COMMENT 'عرض شارات المنتج',
ADD COLUMN `productPageShowPrice` BOOLEAN NOT NULL DEFAULT true COMMENT 'عرض السعر',
ADD COLUMN `productPageShowCountdown` BOOLEAN NOT NULL DEFAULT true COMMENT 'عرض العد التنازلي',
ADD COLUMN `productPageShowStockStatus` BOOLEAN NOT NULL DEFAULT true COMMENT 'عرض حالة المخزون',
ADD COLUMN `productPageShowStockProgress` BOOLEAN NOT NULL DEFAULT true COMMENT 'عرض شريط تقدم المخزون',
ADD COLUMN `productPageShowBackInStock` BOOLEAN NOT NULL DEFAULT true COMMENT 'عرض إشعار عودة المنتج',
ADD COLUMN `productPageShowSecurityBadges` BOOLEAN NOT NULL DEFAULT true COMMENT 'عرض شارات الأمان',
ADD COLUMN `productPageShowSoldNumber` BOOLEAN NOT NULL DEFAULT true COMMENT 'عرض عدد المبيعات',
ADD COLUMN `productPageShowOnlineVisitors` BOOLEAN NOT NULL DEFAULT true COMMENT 'عرض عدد الزوار',
ADD COLUMN `productPageShowEstimatedDelivery` BOOLEAN NOT NULL DEFAULT true COMMENT 'عرض وقت التوصيل المتوقع',
ADD COLUMN `productPageShowFreeShipping` BOOLEAN NOT NULL DEFAULT true COMMENT 'عرض بانر الشحن المجاني',
ADD COLUMN `productPageShowPreOrder` BOOLEAN NOT NULL DEFAULT true COMMENT 'عرض زر الطلب المسبق',
ADD COLUMN `productPageShowVariants` BOOLEAN NOT NULL DEFAULT true COMMENT 'عرض الخيارات (الألوان/المقاسات)',
ADD COLUMN `productPageShowSizeGuide` BOOLEAN NOT NULL DEFAULT true COMMENT 'عرض دليل المقاسات',
ADD COLUMN `productPageShowQuantity` BOOLEAN NOT NULL DEFAULT true COMMENT 'عرض الكمية',
ADD COLUMN `productPageShowVolumeDiscounts` BOOLEAN NOT NULL DEFAULT true COMMENT 'عرض خصومات الكمية',
ADD COLUMN `productPageShowReasonsToPurchase` BOOLEAN NOT NULL DEFAULT true COMMENT 'عرض أسباب الشراء',
ADD COLUMN `productPageShowActions` BOOLEAN NOT NULL DEFAULT true COMMENT 'عرض أزرار الإجراءات',
ADD COLUMN `productPageShowTabs` BOOLEAN NOT NULL DEFAULT true COMMENT 'عرض التبويبات',
ADD COLUMN `productPageShowDescription` BOOLEAN NOT NULL DEFAULT true COMMENT 'عرض الوصف',
ADD COLUMN `productPageShowSKU` BOOLEAN NOT NULL DEFAULT true COMMENT 'عرض رمز المنتج (SKU)',
ADD COLUMN `productPageShowCheckoutForm` BOOLEAN NOT NULL DEFAULT true COMMENT 'عرض نموذج الطلب';

